const SCHEMI_BIBLICI = [
    {
        id: 1,
        parole: [

            { n: 1, d: 'H', x: 0, y: 0, w: 'TAAS', c: 'Nipote di Abraamo, figlio di Nahor e di Reuma (Genesi 22:23,Â 24)' },
            { n: 1, d: 'V', x: 0, y: 0, w: 'TRAE', c: 'â€œLâ€™uomo buono ---- ciÃ² che Ã¨ buono dal buon tesoro del suo cuoreâ€ (Luca 6:45)' },
            { n: 2, d: 'V', x: 1, y: 0, w: 'ARDENTE', c: 'PuÃ² esserlo lâ€™ira o un desiderio (Sofonia 2:2; 1Â Pietro 2:2)' },
            { n: 3, d: 'V', x: 3, y: 0, w: 'SCRIBI', c: 'GesÃ¹ li definÃ¬ ipocriti (Matteo 23:13)' },
            { n: 4, d: 'H', x: 5, y: 0, w: 'LANCE', c: 'Saranno trasformate in cesoie (Isaia 2:4)' },
            { n: 4, d: 'V', x: 5, y: 0, w: 'LAMEC', c: 'Il padre di NoÃ¨ (1Â Cronache 1:3,Â 4)' },
            { n: 7, d: 'V', x: 9, y: 0, w: 'ERMON', c: 'Monte innevato al confine settentrionale d\'Israele. (Salmo 133:3)' },
            { n: 9, d: 'H', x: 3, y: 1, w: 'CLAN', c: 'Gruppo di famiglie discendenti da un ceppo comune (Genesi 25:16)' },
            { n: 11, d: 'H', x: 8, y: 1, w: 'ORO', c: 'Metallo prezioso usato nel tabernacolo e nel tempio. (Esodo 25:11)' },
            { n: 13, d: 'H', x: 0, y: 2, w: 'ADORAM', c: 'capo dei coscritti per i lavori forzati che fu lapidato al tempo di Roboamo (1Â Re 12:18)' },
            { n: 14, d: 'V', x: 7, y: 2, w: 'EUD', c: 'Giudice mancino (Giudici 3:15)' },
            { n: 15, d: 'H', x: 9, y: 2, w: 'ME', c: 'Io' },
            { n: 17, d: 'H', x: 5, y: 4, w: 'CADONO', c: 'Quelli che sono determinati ad arricchirsi (1Tim 6:9)' },
            { n: 18, d: 'V', x: 6, y: 4, w: 'ATENE', c: 'Centro culturale della Grecia visitato da Paolo. (Atti 17:15)' },
            { n: 19, d: 'V', x: 8, y: 4, w: 'ODIO', c: 'Forte avversione o disprezzo, spesso ingiustificato. (1 Giovanni 3:15)' },
            { n: 20, d: 'H', x: 0, y: 5, w: 'ATTI', c: 'Luca mise per iscritto quelli degli apostoli' },
            { n: 20, d: 'V', x: 0, y: 5, w: 'ASDOD', c: 'Importante cittÃ  filistea in cui câ€™era un tempio di Dagon (1Â Samuele 5:1-5)' },
            { n: 22, d: 'H', x: 4, y: 6, w: 'LIEVITO', c: 'Quello dei farisei e dei sadducei andava evitato (Matteo 16:11,Â 12)' },
            { n: 23, d: 'H', x: 2, y: 7, w: 'RUT', c: 'Bisnonna del re Davide (Matteo 1:5,Â 6)' },
            { n: 25, d: 'V', x: 1, y: 8, w: 'LEA', c: 'Moglie di Giacobbe e madre di sei delle dodici tribu. (Genesi 29:23)' },
            { n: 26, d: 'H', x: 4, y: 8, w: 'OREB', c: 'Altro nome del monte Sinai, monte del vero Dio. (Esodo 3:1)' },
            { n: 27, d: 'H', x: 9, y: 8, w: 'UR', c: 'Citta dei caldei da cui parti Abraamo. (Genesi 11:31)' },
            { n: 28, d: 'H', x: 0, y: 9, w: 'DEMA', c: 'AbbandonÃ² Paolo â€˜per amore del presente sistema di coseâ€™ (2Â Timoteo 4:10)' },
            { n: 31, d: 'V', x: 8, y: 9, w: 'EL', c: 'Dio in ebraico' },
            { n: 32, d: 'H', x: 1, y: 10, w: 'ADRAMMELEC', c: 'Dio degli assiri a cui sacrificavano i figli. (2 Re 17:31)' }
        ]
    },
    {
        id: 2,
        parole: [

            { n: 1, d: 'V', x: 1, y: 0, w: 'DAN', c: 'Citta al confine settentrionale d\'Israele. (Giudici 20:1)' },
            { n: 2, d: 'V', x: 5, y: 0, w: 'MARIA', c: 'Nome della madre di Gesu e di altre donne fedeli. (Luca 1:27)' },
            { n: 3, d: 'H', x: 7, y: 0, w: 'LEA', c: 'Moglie di Giacobbe e madre di sei delle dodici tribu. (Genesi 29:23)' },
            { n: 4, d: 'H', x: 0, y: 1, w: 'PANE', c: 'Alimento base, spesso usato come simbolo di sostentamento. (Matteo 6:11)' },
            { n: 6, d: 'H', x: 3, y: 2, w: 'MIRACOLO', c: 'Atto potente che supera le leggi naturali conosciute. (Atti 2:22)' },
            { n: 9, d: 'H', x: 3, y: 3, w: 'ELIU', c: 'Giovane che consiglio Giobbe e i suoi amici. (Giobbe 32:2)' },
            { n: 10, d: 'H', x: 0, y: 4, w: 'GAZA', c: 'Citta filistea dove Sansone fu imprigionato. (Giudici 16:21)' },
            { n: 13, d: 'H', x: 7, y: 4, w: 'AGAG', c: 'Re degli amalechiti risparmiato da Saul. (1 Samuele 15:8)' },
            { n: 17, d: 'H', x: 0, y: 5, w: 'FIRMA', c: 'Marchio o sottoscrizione a convalida di un documento. (Giobbe 31:35)' },
            { n: 18, d: 'H', x: 6, y: 5, w: 'MITRA', c: 'Copricapo cerimoniale del sommo sacerdote. (Esodo 28:4)' },
            { n: 19, d: 'H', x: 0, y: 6, w: 'ZEUS', c: 'Capo degli dei greci, confuso con Barnaba. (Atti 14:12)' },
            { n: 20, d: 'V', x: 5, y: 6, w: 'ACCAD', c: 'Una delle citta fondate da Nimrod. (Genesi 10:10)' },
            { n: 21, d: 'H', x: 7, y: 6, w: 'SEME', c: 'Discendenza o prole; riferito anche al Messia. (Genesi 3:15)' },
            { n: 22, d: 'H', x: 0, y: 7, w: 'AI', c: 'Citta conquistata da Giosue dopo una sconfitta. (Giosue 7:2)' },
            { n: 23, d: 'H', x: 3, y: 7, w: 'LUCA', c: 'Medico e scrittore di un Vangelo e degli Atti. (Colossesi 4:14)' },
            { n: 24, d: 'V', x: 6, y: 7, w: 'ADES', c: 'Soggiorno dei morti, corrispondente all\'ebraico Sceol. (Atti 2:31)' },
            { n: 25, d: 'H', x: 8, y: 7, w: 'VIA', c: 'Termine usato per indicare il modo di vivere cristiano. (Atti 9:2)' },
            { n: 26, d: 'V', x: 2, y: 8, w: 'ASA', c: 'Re di Giuda noto per la sua lotta all\'idolatria. (1 Re 15:9)' },
            { n: 28, d: 'H', x: 8, y: 8, w: 'WOL', c: 'Acronimo per la biblioteca online dei testimoni di Geova. (Glossario)' },
            { n: 29, d: 'H', x: 0, y: 9, w: 'SUSA', c: 'Capitale dell\'impero persiano ai tempi di Ester. (Ester 2:8)' },
            { n: 33, d: 'H', x: 8, y: 9, w: 'ORO', c: 'Metallo prezioso usato nel tabernacolo e nel tempio. (Esodo 25:11)' },
            { n: 34, d: 'H', x: 1, y: 10, w: 'DAN', c: 'Citta al confine settentrionale d\'Israele. (Giudici 20:1)' },
            { n: 36, d: 'H', x: 8, y: 10, w: 'UR', c: 'Citta dei caldei da cui parti Abraamo. (Genesi 11:31)' }
        ]
    },
    {
        id: 3,
        parole: [

            { n: 1, d: 'H', x: 0, y: 0, w: 'GLOSSOLALIA', c: 'Dono miracoloso di parlare in lingue diverse. (1 Corinti 12:10)' },
            { n: 1, d: 'V', x: 0, y: 0, w: 'GOG', c: 'Nome simbolico del nemico che attacca il popolo di Dio. (Ezechiele 38:2)' },
            { n: 2, d: 'V', x: 1, y: 0, w: 'LEA', c: 'Moglie di Giacobbe e madre di sei delle dodici tribu. (Genesi 29:23)' },
            { n: 11, d: 'H', x: 3, y: 1, w: 'CRETA', c: 'Isola del Mediterraneo visitata da Paolo. (Atti 27:7)' },
            { n: 12, d: 'H', x: 9, y: 1, w: 'UR', c: 'Citta dei caldei da cui parti Abraamo. (Genesi 11:31)' },
            { n: 13, d: 'H', x: 0, y: 2, w: 'GALAAD', c: 'Regione montuosa nota per il suo balsamo. (Geremia 8:22)' },
            { n: 15, d: 'H', x: 7, y: 2, w: 'ROMA', c: 'Capitale dell\'impero e sesta potenza mondiale. (Atti 18:2)' },
            { n: 16, d: 'H', x: 4, y: 3, w: 'PALO', c: 'Vedi Strumento di tortura; legno usato per le esecuzioni. (Matteo 27:32)' },
            { n: 17, d: 'V', x: 5, y: 3, w: 'ANACHITI', c: 'Popolo di alta statura che spavento le spie. (Numeri 13:22)' },
            { n: 18, d: 'H', x: 9, y: 3, w: 'RE', c: 'Sovrano che esercita l\'autorita su un popolo. (1 Samuele 8:5)' },
            { n: 19, d: 'H', x: 0, y: 4, w: 'CHISON', c: 'Torrente che travolse l\'esercito di Sisera. (Giudici 5:21)' },
            { n: 19, d: 'V', x: 0, y: 4, w: 'CARMELO', c: 'Promontorio dove Elia sfido i profeti di Baal. (1 Re 18:19)' },
            { n: 23, d: 'H', x: 8, y: 4, w: 'GAT', c: 'Citta d\'origine del gigante Golia. (1 Samuele 17:4)' },
            { n: 23, d: 'V', x: 8, y: 4, w: 'GOLGOTA', c: 'Luogo del teschio, dove Gesu fu messo al palo. (Matteo 27:33)' },
            { n: 24, d: 'H', x: 0, y: 5, w: 'ABERRAZIONE', c: 'Pratica o idolo detestabile agli occhi di Dio. (Geremia 7:30)' },
            { n: 25, d: 'H', x: 0, y: 7, w: 'MOAB', c: 'Altopiano a est del Mar Morto. (Genesi 19:37)' },
            { n: 26, d: 'V', x: 1, y: 7, w: 'OREB', c: 'Altro nome del monte Sinai. (Esodo 3:1)' },
            { n: 27, d: 'V', x: 2, y: 7, w: 'ASIA', c: 'Provincia romana dove si trovavano le sette congregazioni. (Rivelazione 1:4)' },
            { n: 28, d: 'V', x: 3, y: 7, w: 'BOAZ', c: 'Uomo di Betlemme che sposo Rut. (Rut 2:1)' },
            { n: 29, d: 'H', x: 7, y: 7, w: 'AGAG', c: 'Re degli amalechiti risparmiato da Saul. (1 Samuele 15:8)' },
            { n: 29, d: 'V', x: 7, y: 7, w: 'ANNA', c: 'Profetessa ottantenne presente al tempio. (Luca 2:36)' },
            { n: 30, d: 'V', x: 9, y: 7, w: 'AMEN', c: 'Significa cosi sia o sicuramente. (Deuteronomio 27:15)' },
            { n: 31, d: 'V', x: 10, y: 7, w: 'GESU', c: 'Nome del Figlio di Dio, il Messia promesso. (Matteo 1:21)' },
            { n: 33, d: 'H', x: 7, y: 8, w: 'NOME', c: 'Designazione che identifica la persona o Dio. (Esodo 3:15)' }
        ]
    },
    {
        id: 4,
        parole: [

            { n: 1, d: 'H', x: 0, y: 0, w: 'BEGA', c: 'Litigio' },
            { n: 1, d: 'V', x: 0, y: 0, w: 'BENEDIZIONE', c: 'Favore divino o lode rivolta a Dio. (Numeri 6:24)' },
            { n: 2, d: 'V', x: 1, y: 0, w: 'EGO', c: 'Di chi ha presunzione' },
            { n: 3, d: 'V', x: 2, y: 0, w: 'GERUSALEMME', c: 'Citta santa e sede del tempio di Geova. (2 Samuele 5:5)' },
            { n: 4, d: 'H', x: 5, y: 0, w: 'AMASA', c: 'Nipote di Davide e capo dell\'esercito di Assalonne. (2 Samuele 17:25)' },
            { n: 6, d: 'H', x: 7, y: 0, w: 'ASA', c: 'Re di Giuda noto per la sua lotta all\'idolatria. (1 Re 15:9)' },
            { n: 7, d: 'V', x: 8, y: 0, w: 'SALDO', c: 'Stabile e incrollabile nella fede. (1 Corinti 15:58)' },
            { n: 10, d: 'H', x: 4, y: 1, w: 'ARARAT', c: 'Monti su cui si poso l\'arca dopo il Diluvio. (Genesi 8:4)' },
            { n: 11, d: 'H', x: 0, y: 2, w: 'NORMA', c: 'Regola di condotta stabilita da Dio. (Salmo 119:105)' },
            { n: 12, d: 'H', x: 6, y: 2, w: 'EGLON', c: 'Re di Moab che oppresse Israele. (Giudici 3:12)' },
            { n: 13, d: 'H', x: 4, y: 3, w: 'DECADE', c: 'Periodo di dieci giorni o anni. (Glossario)' },
            { n: 15, d: 'H', x: 0, y: 4, w: 'DISCEPOLO', c: 'Chi impara e segue gli insegnamenti di un maestro. (Matteo 28:19)' },
            { n: 16, d: 'V', x: 10, y: 4, w: 'IO', c: 'PerchÃ©...possa rispondere (Per 27:11)' },
            { n: 17, d: 'H', x: 4, y: 5, w: 'NEBO', c: 'Monte da cui Mose vide la Terra Promessa. (Deuteronomio 34:1)' },
            { n: 17, d: 'V', x: 4, y: 5, w: 'NOE', c: 'Costruttore dell\'arca e sopravvissuto al Diluvio. (Genesi 6:8)' },
            { n: 18, d: 'H', x: 9, y: 5, w: 'CO', c: 'Presso (suffisso)' },
            { n: 18, d: 'V', x: 9, y: 5, w: 'CANA', c: 'Luogo del primo miracolo dell\'acqua in vino. (Giovanni 2:1)' },
            { n: 19, d: 'H', x: 0, y: 6, w: 'ZOLFO', c: 'Sostanza infiammabile simbolo di distruzione. (Rivelazione 21:8)' },
            { n: 22, d: 'H', x: 6, y: 6, w: 'CEFA', c: 'Nome aramaico dato a Simon Pietro. (Giovanni 1:42)' },
            { n: 24, d: 'H', x: 0, y: 7, w: 'IZEBEL', c: 'Regina malvagia (1Re 22:23)' },
            { n: 26, d: 'H', x: 7, y: 7, w: 'INNO', c: 'Canto di lode o ringraziamento rivolto a Dio. (Colossesi 3:16)' },
            { n: 28, d: 'H', x: 2, y: 8, w: 'MA', c: 'Alternativa a se...' },
            { n: 29, d: 'H', x: 5, y: 8, w: 'BASCAN', c: 'Regione dei tori. (Salmo 22:12)' },
            { n: 30, d: 'H', x: 0, y: 9, w: 'NEMICO', c: 'Chi si oppone a Dio o al suo popolo. (Matteo 13:39)' },
            { n: 33, d: 'H', x: 7, y: 9, w: 'SE', c: 'Alternativa a ma...' },
            { n: 34, d: 'H', x: 0, y: 10, w: 'EFESO', c: 'Metropoli dell\'Asia Minore nota per il tempio di Artemide. (Atti 19:1)' },
            { n: 35, d: 'H', x: 6, y: 10, w: 'BAAL', c: 'Dio cananeo della fertilita e dei cieli. (Giudici 2:13)' }
        ]
    },
    {
        id: 5,
        parole: [

            { n: 1, d: 'H', x: 1, y: 0, w: 'ALFA', c: 'La prima lettera dell’alfabeto greco (Rivelazione 21:6)' },
            { n: 1, d: 'V', x: 1, y: 0, w: 'ARCA', c: 'Uzza morì per averla toccata (2 Samuele 6:6, 7)' },
            { n: 4, d: 'H', x: 6, y: 0, w: 'SPIE', c: 'Raab dimostrò la sua fede ospitandole (Ebrei 11:31)' },
            { n: 5, d: 'V', x: 7, y: 0, w: 'PORPORA', c: 'Colore e tessuto pregiato simbolo di regalita. (Marco 15:17)' },
            { n: 6, d: 'V', x: 9, y: 0, w: 'ELIU', c: 'Giovane che consiglio Giobbe e i suoi amici. (Giobbe 32:2)' },
            { n: 7, d: 'H', x: 0, y: 1, w: 'UR', c: 'Citta dei caldei da cui parti Abraamo. (Genesi 11:31)' },
            { n: 8, d: 'H', x: 3, y: 1, w: 'AGGEO', c: 'Profetizzò al tempo della ricostruzione del tempio (Esdra 6:14)' },
            { n: 9, d: 'H', x: 9, y: 1, w: 'LU', c: 'Luca' },
            { n: 10, d: 'H', x: 1, y: 2, w: 'CIRO', c: 'Re di Persia che libero gli ebrei da Babilonia. (Esdra 1:1)' },
            { n: 11, d: 'H', x: 6, y: 2, w: 'ARMI', c: 'Quelle dei cristiani non sono carnali (2 Corinti 10:4)' },
            { n: 12, d: 'V', x: 0, y: 3, w: 'FRATELLO', c: 'Membro della stessa famiglia o della congregazione. (Matteo 23:8)' },
            { n: 13, d: 'V', x: 5, y: 3, w: 'EDOM', c: 'Regione montuosa a sud del Mar Morto. (Genesi 36:8)' },
            { n: 15, d: 'V', x: 10, y: 3, w: 'OSCURITA', c: 'Assenza di luce, simbolo di ignoranza o male. (Isaia 60:2)' },
            { n: 16, d: 'H', x: 2, y: 4, w: 'ABADDON', c: 'Termine ebraico che significa distruzione. (Rivelazione 9:11)' },
            { n: 19, d: 'H', x: 0, y: 5, w: 'ADES', c: 'Soggiorno dei morti, corrispondente all\'ebraico Sceol. (Atti 2:31)' },
            { n: 20, d: 'V', x: 1, y: 5, w: 'DARIO', c: 'Nome di diversi re medi e persiani. (Esdra 4:5)' },
            { n: 21, d: 'H', x: 7, y: 5, w: 'RE', c: 'Sovrano che esercita l\'autorita su un popolo. (1 Samuele 8:5)' },
            { n: 23, d: 'H', x: 3, y: 6, w: 'SEME', c: 'Discendenza o prole; riferito anche al Messia. (Genesi 3:15)' },
            { n: 24, d: 'V', x: 4, y: 6, w: 'ELI', c: 'Sommo sacerdote e giudice che educo Samuele. (1 Samuele 1:9)' },
            { n: 25, d: 'V', x: 6, y: 6, w: 'ETA', c: 'Periodo della vita o epoca storica specifica. (Glossario)' },
            { n: 26, d: 'V', x: 9, y: 6, w: 'CANA', c: 'Luogo del primo miracolo dell\'acqua in vino. (Giovanni 2:1)' },
            { n: 27, d: 'H', x: 0, y: 7, w: 'ERA', c: 'Arco temporale' },
            { n: 30, d: 'H', x: 3, y: 8, w: 'DINA', c: 'Figlia di Giacobbe e Lia. (Genesi 30:21)' },
            { n: 32, d: 'H', x: 0, y: 9, w: 'LOGO', c: 'Termine greco per parola o ragione; riferito a Gesu. (Giovanni 1:1)' },
            { n: 34, d: 'H', x: 8, y: 9, w: 'GAT', c: 'Citta d\'origine del gigante Golia. (1 Samuele 17:4)' },
            { n: 35, d: 'H', x: 2, y: 10, w: 'GRAVOSI', c: 'Pesanti, onerosi (1 Giovanni 5:3)' }
        ]
    },
        {
            id: 6,
        parole: [

            { n: 1, d: 'H', x: 0, y: 0, w: 'SEME', c: 'Discendenza o prole; riferito anche al Messia. (Genesi 3:15)' },
            { n: 1, d: 'V', x: 0, y: 0, w: 'SAUL', c: 'Il primo re di Israele (Atti 13:21)' },
            { n: 3, d: 'V', x: 3, y: 0, w: 'ERBE', c: 'Quelle amare si mangiavano durante la Pasqua (Numeri 9:11)' },
            { n: 4, d: 'H', x: 5, y: 0, w: 'TRIBU', c: 'Ciascuna delle dodici divisioni del popolo d\'Israele. (Genesi 49:28)' },
            { n: 4, d: 'V', x: 5, y: 0, w: 'TINI', c: 'Quando traboccano, c’è abbondanza (Proverbi 3:10)' },
            { n: 5, d: 'V', x: 7, y: 0, w: 'IAH', c: 'Forma poetica del nome “Geova” (Esodo 15:1, 2)' },
            { n: 6, d: 'V', x: 9, y: 0, w: 'UNTO', c: 'Scelto e incaricato tramite l\'unzione spirituale. (2 Corinti 1:21)' },
            { n: 7, d: 'H', x: 2, y: 1, w: 'ARMI', c: 'Quelle dei cristiani non sono carnali (2 Corinti 10:4)' },
            { n: 9, d: 'V', x: 10, y: 1, w: 'RE', c: 'Sovrano che esercita l\'autorita su un popolo. (1 Samuele 8:5)' },
            { n: 11, d: 'V', x: 1, y: 2, w: 'FUMO', c: 'Dà fastidio agli occhi (Proverbi 10:26)' },
            { n: 13, d: 'V', x: 6, y: 2, w: 'CORA', c: 'Levita che guido la ribellione contro Mose. (Numeri 16:1)' },
            { n: 14, d: 'V', x: 8, y: 2, w: 'ENOC', c: 'Uomo fedele che cammino con il vero Dio. (Genesi 5:22)' },
            { n: 15, d: 'H', x: 0, y: 3, w: 'LUCE', c: 'Simbolo di verita, santita e guida divina. (Salmo 119:105)' },
            { n: 16, d: 'V', x: 2, y: 3, w: 'COMPAGNO', c: 'Lo era di prigionia per Paolo (Colossesi 4:10)' },
            { n: 20, d: 'V', x: 4, y: 4, w: 'HIN', c: 'Misura di capacità per liquidi (Esodo 29:40)' },
            { n: 21, d: 'H', x: 6, y: 4, w: 'REO', c: 'Colpevole (Marco 14:64)' },
            { n: 22, d: 'V', x: 10, y: 4, w: 'API', c: 'Producono il miele (Giudici 14:8)' },
            { n: 23, d: 'H', x: 0, y: 5, w: 'SOMMITA', c: 'La parte più alta (2 Samuele 14:25)' },
            { n: 23, d: 'V', x: 0, y: 5, w: 'SINAR', c: 'Il paese in cui sorse la torre di Babele (Genesi 11:2-4)' },
            { n: 25, d: 'V', x: 5, y: 5, w: 'TABOR', c: 'Monte della Galilea dove Barac raduno l\'esercito. (Giudici 4:6)' },
            { n: 27, d: 'V', x: 9, y: 5, w: 'GEENA', c: 'Simbolo di distruzione eterna, dalla valle di Innom. (Matteo 5:22)' },
            { n: 28, d: 'H', x: 2, y: 6, w: 'PENA', c: 'Dolore, sofferenza (Romani 9:2)' },
            { n: 29, d: 'V', x: 7, y: 6, w: 'LEA', c: 'Moglie di Giacobbe e madre di sei delle dodici tribu. (Genesi 29:23)' },
            { n: 31, d: 'H', x: 0, y: 7, w: 'NAAS', c: 'Re ammonita che voleva cavare un occhio a tutti gli abitanti di Iabes di Galaad (1 Samuele 11:1, 2)' },
            { n: 32, d: 'H', x: 5, y: 7, w: 'BREVE', c: 'Lo è il periodo di tempo che ha a disposizione Satana (Rivelazione 12:12)' },
            { n: 33, d: 'H', x: 2, y: 8, w: 'GAIO', c: 'Il destinatario della terza lettera di Giovanni (3 Giovanni 1)' },
            { n: 36, d: 'V', x: 10, y: 8, w: 'NOE', c: 'Costruttore dell\'arca e sopravvissuto al Diluvio. (Genesi 6:8)' },
            { n: 37, d: 'H', x: 0, y: 9, w: 'RANCORE', c: 'Non bisogna nutrirlo (Levitico 19:18)' },
            { n: 38, d: 'V', x: 1, y: 9, w: 'AI', c: 'Citta conquistata da Giosue dopo una sconfitta. (Giosue 7:2)' },
            { n: 41, d: 'H', x: 1, y: 10, w: 'IO', c: 'me' },
            { n: 42, d: 'H', x: 6, y: 10, w: 'VIA', c: 'Termine usato per indicare il modo di vivere cristiano. (Atti 9:2)' }
        ]
    }
];
